pub static VERBS: &[&str] = &[
    "slipped on",
    "shot",
    "danced on",
    "pranced on",
    "took",
    "stole",
    "switched on",
    "switched off",
    "ran over",
    "destroyed",
    "broke",
    "shattered",
    "obliterated",
    "turned on",
    "turned off",
    "flew over",
    "flew under",
    "bowed down to",
    "went to the bathroom with",
    "went inside",
    "blew away",
    "threw away",
    "threw",
    "kidnapped",
    "played with",
    "pranked",
    "dislodged",
    "ate",
    "drank",
];
